services:
  app:
    build: .
    ports:
      - "8082:3000" # external 8082 → container 3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=guacamaya_productos
      - DB_USER=postgres
      - DB_PASSWORD=ikEvs1crXV2ewH4SD0v0
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: guacamaya_productos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ikEvs1crXV2ewH4SD0v0
    ports:
      - "5435:5432" # external 5435 to avoid conflict with auth
    volumes:
      - pgdata_productos:/var/lib/postgresql/data

volumes:
  pgdata_productos:
